### ISSUE TITLE
不好使  三个盘 一个 都找不到

### ISSUE THREAD

**Issue by google-biaoge** [Neo-Maoku/SearchAvailableExe#3]
根本不好使 
![微信图片_20240416014142](https://github.com/Neo-Maoku/SearchAvailableExe/assets/166842436/03a50047-7eb1-4961-9ea6-f60087d6edbd)
![Uploading 微信图片_20240416014142.png…]()

**Comment by Neo-Maoku** [comment]
可能是程序报错，你试下最新版。Test文件夹中有测试程序，你扫那个目录看看

**Comment by blu3evil** [comment]
把TestLoad_x86.dll也移到这个目录下，不然扫描到32位可利用白程序时会崩溃

**Comment by Neo-Maoku** [comment]
是的，这个是正确的
