### ISSUE TITLE
执行完搜索后上线的CS又自动掉线

### ISSUE THREAD

**Issue by Zer08Bytes** [Neo-Maoku/SearchAvailableExe#5]
执行完搜索后上线的CS又自动掉线
SearchAvailableExe64.exe -i "C:" -s -o result.txt
这个执行完以后  上线的cs等到搜索命令执行完毕，就又自动掉线了

![图片](https://github.com/Neo-Maoku/SearchAvailableExe/assets/41458106/d3bfad7b-a782-4116-9a1d-7c7d3a4ec74a)

**Comment by Neo-Maoku** [comment]
这个是正常的，因为上线功能是做测试的，会在进程启动3秒关闭。

**Comment by Zer08Bytes** [comment]
请问，这个3秒的时间设定，是在源代码的哪个地方呢？我想修改时间为10秒或者更久一点，谢谢




zer0
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Neo-Maoku/SearchAvailableExe"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月7日(星期二) 上午10:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Neo-Maoku/SearchAvailableExe] 执行完搜索后上线的CS又自动掉线 (Issue #5)





 
这个是正常的，因为上线功能是做测试的，会在进程启动3秒关闭。
